version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro

  logger:
    build: 
      context: .
      dockerfile: Dockerfile.logger
    volumes:
      - ./logs:/logs
